version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
    - echo installing maven...
    - sudo yum update
    - sudo yum install java-1.8.0-openjdk-devel
    - sudo yum install maven
  build:
    commands:
    - echo building the justiceleague-tracker
    - mvn install
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'
